import type { Metadata } from "next";
import Sidebar from '@/components/sample/sidebar/sidebar';

// head 태그에 들어갈 메타데이터 정보
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// next.js에서는 기본 레이아웃이 존재함. layout이 page를 감싸서 children 컴포넌트를 렌더링함
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <Sidebar />
      <div className="flex-1 p-4 ml-64">
        {children}
      </div>
    </div>
  );
}