import type { Metadata } from "next";
import localFont from "next/font/local";
import 'jotai-devtools/styles.css';
import "./globals.css";
import Providers from "./query-client-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// head 태그에 들어갈 메타데이터 정보
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// next.js에서는 기본 레이아웃이 존재함. layout이 page를 감싸서 children컴포넌트를 렌더링함
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
